---
- name: Remove monitoring stack using helm
  hosts: server
  become: true
  vars_files:
   - ../../../configs/vault.yml
  roles:
    - role: remove-monitoring-stack

- name: Remove monitoring-stack installation marker file
  file:
    path: /var/lib/monitoring-stack/monitoring-stack-installed
    state: absent
  become: true
  register: monitoring_stack_marker_removed