---
- name: Ensure NFS server IP variable is defined
  fail:
    msg: "The variable 'hostvars[inventory_hostname]['internal_ip']' is not defined in the inventory."
  when: hostvars[inventory_hostname]['internal_ip'] is not defined

- name: Ensure NFS export path variable is defined
  fail:
    msg: "The variable 'export_path' is not defined in the inventory."
  when: export_path is not defined

- name: Ensure NFS client mount point variable is defined
  fail:
    msg: "The variable 'export_path' is not defined in the inventory."
  when: export_path is not defined

- name: Install NFS client utilities
  apt:
    name: nfs-common
    state: present
    update_cache: true
  become: true

- name: Ensure the mount point exists
  file:
    path: "{{ export_path }}"
    state: directory
    mode: "0755"
  become: true

- name: Check if the NFS share is already mounted
  shell: mount | grep "{{ export_path }}"
  register: mount_check
  changed_when: false
  failed_when: false 

- name: Mount the NFS share if not already mounted
  mount:
    path: "{{ export_path }}"
    src: "{{ hostvars[groups['server'][0]]['internal_ip'] }}:{{ export_path }}"
    fstype: nfs
    opts: defaults
    state: mounted
  when: mount_check.rc != 0
  changed_when: mount_check.rc == 0
  become: true

- name: Ensure /etc/fstab entry for the NFS share (ensure remount after reboot)
  lineinfile:
    path: /etc/fstab
    line: "{{ hostvars[inventory_hostname]['internal_ip'] }}:{{ export_path }} {{ export_path }} nfs defaults 0 0"
    state: present
  become: true

- name: Verify the NFS share is accessible
  shell: ls "{{ export_path }}"
  register: share_access
  changed_when: false

- name: Fail if the NFS share is not accessible
  fail:
    msg: "The NFS share {{ hostvars[inventory_hostname]['internal_ip'] }}:{{ export_path }} could not be accessed from {{ export_path }}."
  when: share_access.rc != 0

- name: Confirm the NFS share is successfully mounted
  debug:
    msg: "The NFS share {{ hostvars[inventory_hostname]['internal_ip'] }}:{{ export_path }} is successfully mounted on {{ export_path }}."
