k3s_cluster:
  children:
    server:
      hosts:
    agent:
      hosts:

  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: ubuntu  # Matches your user for SSH access

    rancher_hostname: rancher.local
    bootstrapPassword: "{{ ansible_vault.bootstrapPassword }}"