---
- name: Install and configure Ubuntu pod with kubectl
  hosts: server
  become: true
  vars_files:
   - ../../../configs/vault.yml
  roles:
  #  - deploy-benchmarking-pod
   - deploy-pods-high-cpu
   - deploy-pods-high-mem
   - install-tools
  #  - setup-openssh
  #  - install-kubecontrol
  #  - post-install-cleanup