---
- name: Delete config/values files from target machine
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/ubuntu-kubectl-pod.yml
  become: true

# - name: Delete config/values files from control machine
#   file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - /tmp/ubuntu-kubectl-pod.yml
#   delegate_to: localhost
#   run_once: true
#   become: false
