---
- name: Ensure /root/kbench directory is removed before cloning
  command: |
    kubectl exec -n {{ benchmarking_namespace }} ubuntu-benchmark -- bash -c "rm -rf /root/kbench"
  register: cleanup_kbench
  failed_when: cleanup_kbench.rc != 0

- name: Clone the k-bench repository
  command: |
    kubectl exec -n {{ benchmarking_namespace }} ubuntu-benchmark -- bash -c "git clone {{ k_bench_repo }} /root/kbench"

- name: Build and install k-bench
  command: |
    kubectl exec -n {{ benchmarking_namespace }} ubuntu-benchmark -- bash -c "cd /root/kbench && . install.sh"
  register: kbench_install
  failed_when: kbench_install.rc != 0

- name: Install missing Go dependencies
  command: |
    kubectl exec -n {{ benchmarking_namespace }} ubuntu-benchmark -- bash -c "cd /root/kbench && go get golang.org/x/oauth2/google@v0.0.0-20200107190931-bf48bf16ab8d"

- name: Build and install k-bench
  command: |
    kubectl exec -n {{ benchmarking_namespace }} ubuntu-benchmark -- bash -c "cd /root/kbench && go install cmd/kbench.go"
  register: kbench_install
  failed_when: kbench_install.rc != 0
