apiVersion: tycho.testing/v1
kind: TestPlan
metadata:
  plan_id: "cpu-burst-train-v1"
  description: "Slice 4: CPU burst train with baseline vs burst levels (single pod)"

spec:
  target:
    node_name: "srv-lab-t-737"
    namespace: "tycho-test"

  repetitions:
    count: 1

  timing:
    margin_before_sec: 10
    margin_after_sec: 10

  phases:
    - name: "warmup"
      type: "sleep"
      duration_sec: 10

    - name: "burst_train"
      type: "workload"
      workload:
        template: "stressng-cpu-burst"
        params:
          # overall structure
          total_duration_sec: 180
          on_sec: 9
          off_sec: 9
          seed: 1

          # ON: burst level
          on_workers: 10
          on_method: "matrixprod"

          # OFF: baseline level (choose: sleep OR stress)
          off_mode: "stress"
          off_workers: 1
          off_method: "matrixprod"

          # single-pod constraint: request must cover the maximum level
          cpu_request_mcpu: 10000
          # optional future knobs (runner may ignore initially)
          cpu_limit_mcpu: 0

    - name: "cooldown"
      type: "sleep"
      duration_sec: 10
