apiVersion: tycho.testing/v1
kind: TestPlan
metadata:
  plan_id: "cpu-burst-baseline-v1"
  description: "Slice 4: CPU burst train with baseline stress (1 core) and bursts (10 cores)"

spec:
  target:
    node_name: "srv-lab-t-737"
    namespace: "tycho-test"

  repetitions:
    count: 1

  timing:
    margin_before_sec: 10
    margin_after_sec: 10

  phases:
    - name: "warmup"
      type: "sleep"
      duration_sec: 10

    - name: "burst_train"
      type: "workload"
      workload:
        template: "stressng-cpu-burst"
        params:
          total_duration_sec: 180
          on_sec: 9
          off_sec: 9
          seed: 1

          on_workers: 10
          on_method: "matrixprod"

          off_mode: "stress"
          off_workers: 1
          off_method: "matrixprod"

          cpu_request_mcpu: 10000
          cpu_limit_mcpu: 0

    - name: "cooldown"
      type: "sleep"
      duration_sec: 10
