apiVersion: tycho.testing/v1
kind: TestPlan
metadata:
  plan_id: "cpu-warmup-ramp-test-v1"
  description: "Acceptance: warmup + ramp-to-50c/200s + test + cooldown"

spec:
  target:
    node_name: "srv-lab-t-737"
    namespace: "tycho-test"

  repetitions:
    count: 1

  timing:
    margin_before_sec: 10
    margin_after_sec: 10

  phases:
    - name: "warmup"
      type: "sleep"
      duration_sec: 10

    - name: "precondition"
      type: "ramp"
      ramp_profile: "cpu"
      duration_sec: 200
      params:
        max_workers: 2
        step_count: 5
        method: "matrixprod"
        cpu_request_mcpu: 50000

    - name: "cooldown"
      type: "sleep"
      duration_sec: 10
