apiVersion: tycho.testing/v1
kind: TestPlan
metadata:
  plan_id: "cpu-short-lived-v1"
  description: "Prototype: short-lived CPU bursts"

spec:
  target:
    node_name: "srv-lab-t-737"
    namespace: "tycho-test"

  repetitions:
    count: 1

  timing:
    margin_before_sec: 10
    margin_after_sec: 10

  phases:
    - name: "warmup"
      type: "sleep"
      duration_sec: 10

    - name: "test"
      type: "workload"
      workload:
        template: "stressng-cpu"
        params:
          workers: 20
          method: "matrixprod"
          duration_sec: 5
          cpu_request_mcpu: 2000

    - name: "cooldown"
      type: "sleep"
      duration_sec: 10
