apiVersion: tycho.testing/v1
kind: TestPlan
metadata:
  plan_id: "gpu-burn-steady-3-pod"
  description: "run pods at the same time"

spec:
  target:
    node_name: "srv-lab-t-737"
    namespace: "tycho-test"

  repetitions:
    count: 1

  timing:
    margin_before_sec: 10
    margin_after_sec: 10

  phases:
    # - name: "warmup"
    #   type: "sleep"
    #   duration_sec: 15


    - name: "pair"                     # simultaneous workloads are possible
      type: "workload_set"
      workloads:
        - name: "gpu-burn-steady-1"
          template: "gpu-burn-steady"
          params:
            duration_sec: 120
            gpu_request_count: 1
            gpu_burn_list_gpus: true
            gpu_burn_mem_pct: 90
            gpu_burn_use_doubles: false
            gpu_burn_use_tensor_cores: true
            cpu_request_mcpu: 1000
            cpu_limit_mcpu: 0
        - name: "gpu-burn-steady-2"
          template: "gpu-burn-steady"
          params:
            duration_sec: 120
            gpu_request_count: 1
            gpu_burn_list_gpus: true
            gpu_burn_mem_pct: 90
            gpu_burn_use_doubles: false
            gpu_burn_use_tensor_cores: true
            cpu_request_mcpu: 1000
            cpu_limit_mcpu: 0 


    - name: "cooldown"
      type: "sleep"
      duration_sec: 15
