---
# - name: Install monitoring_stack using Helm
#   shell: |
#     helm uninstall monitoring-stack monitoring-stack/kube-prometheus-stack \
#       --n {{ monitoring_namespace }}
#   environment:
#     KUBECONFIG: /home/ubuntu/.kube/config

- name: Remove monitoring-stack installation marker file
  file:
    path: /var/lib/monitoring-stack/monitoring-stack-installed
    state: absent
  become: true
  register: monitoring_stack_marker_removed