---
- name: Install monitoring_stack using Helm
  shell: |
    helm uninstall monitoring --n {{ monitoring_namespace }}
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

# - name: Install monitoring_stack using Helm                   ##this is really bad
#   shell: |
#     kube --n {{ monitoring_namespace }}
#   environment:
#     KUBECONFIG: /home/ubuntu/.kube/config

# - name: Install monitoring_stack using Helm
#   shell: |
#     helm uninstall monitoring --n {{ monitoring_namespace }}
#   environment:
#     KUBECONFIG: /home/ubuntu/.kube/config

# - name: Install monitoring_stack using Helm
#   shell: |
#     helm uninstall monitoring --n {{ monitoring_namespace }}
#   environment:
#     KUBECONFIG: /home/ubuntu/.kube/config


- name: Remove monitoring-stack installation marker file      # DOES NOT WORK
  file:
    path: /var/lib/monitoring-stack/monitoring-stack-installed
    state: absent
  become: true
  register: monitoring_stack_marker_removed
