---
- name: Prepare SSD on master server
  hosts: server
  become: true
  #vars_files:
  #  - ../../configs/vault.yml
  roles:
    - role: format_ssd

#- name: Install and configure NFS server
#  hosts: server
#  vars_files:
#    - ../../configs/vault.yml
#  roles:
#    - role: nfs_server

#- name: Install and configure NFS clients
#  hosts: agent
#  vars_files:
#    - ../../configs/vault.yml
#  roles:
#    - role: nfs_client
  # vars:
  #   nfs_server_ip: "{{ hostvars['master1']['ansible_host'] }}"

#- name: Configure Kubernetes Persistent Volumes and Claims
#  hosts: server
#  vars_files:
#    - ../../configs/vault.yml
#  roles:
#    - role: kubernetes_pv_pvc
  #vars:
  #  nfs_server_ip: "{{ hostvars['master1']['ansible_host'] }}"