---
- name: Check if kube-burner namespace exists
  command: kubectl get namespace kube-burner
  register: namespace_check
  ignore_errors: true

- name: Create kube-burner namespace if necessary
  when: namespace_check.rc != 0
  command: kubectl create namespace kube-burner
  ignore_errors: true

- name: Create kube-burner pod manifest
  copy:
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-burner
        namespace: kube-burner
        labels:
          app: kube-burner
      spec:
        containers:
        - name: kube-burner
          image: quay.io/kube-burner/kube-burner:latest
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
    dest: /tmp/kube-burner-pod.yml

- name: Deploy the kube-burner pod
  command: kubectl apply -f /tmp/kube-burner-pod.yml
  register: deploy_kube_burner
  changed_when: "'created' in deploy_kube_burner.stdout"

- name: Wait for kube-burner pod to be ready
  command: kubectl wait --for=condition=ready pod/kube-burner -n kube-burner --timeout=300s
  register: wait_kube_burner_ready
  failed_when: wait_kube_burner_ready.rc != 0

# - name: Install kubectl on kube-burner pod
#   command: |
#     kubectl exec -n kube-burner kube-burner -- bash -c "curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/"
#   register: install_kubectl_kube_burner
#   failed_when: install_kubectl_kube_burner.rc != 0

# - name: Copy kubeconfig to kube-burner pod
#   copy:
#     src: ~/.kube/config
#     dest: /tmp/kubeconfig
  # delegate_to: localhost

# - name: Transfer kubeconfig to kube-burner pod
#   command: |
#     kubectl cp /tmp/kubeconfig kube-burner/kube-burner:/root/.kube/config
#   register: transfer_kubeconfig
#   failed_when: transfer_kubeconfig.rc != 0

# - name: Ensure kube-burner binary is executable in the pod
#   command: |
#     kubectl exec -n kube-burner kube-burner -- bash -c "chmod +x /usr/local/bin/kube-burner"
#   register: ensure_kube_burner_binary
#   failed_when: ensure_kube_burner_binary.rc != 0

- name: Run kube-burner workload
  command: |
    kubectl exec -n kube-burner kube-burner -- bash -c "kube-burner init -c /root/workload-config.yml"
  register: run_kube_burner_workload
  failed_when: run_kube_burner_workload.rc != 0
