---
- name: Ensure the specified disk variable is defined
  fail:
    msg: "The variable 'disk_for_persistent_storage' is not defined in the inventory."
  when: disk_for_persistent_storage is not defined

- name: Ensure the export path variable is defined
  fail:
    msg: "The variable 'export_path' is not defined in the inventory."
  when: export_path is not defined

- name: Ensure the NFS network variable is defined
  fail:
    msg: "The variable 'nfs_network' is not defined in the inventory."
  when: nfs_network is not defined

- name: Ensure the mount point exists
  file:
    path: "{{ export_path }}"
    state: directory

- name: Check if the disk is mounted
  shell: mount | grep "{{ export_path }}"
  register: mount_check
  changed_when: false
  failed_when: false

- name: Mount the disk if not already mounted
  mount:
    path: "{{ export_path }}"
    src: "{{ disk_for_persistent_storage }}1"
    fstype: btrfs
    opts: defaults
    state: mounted
  when: mount_check.rc != 0
  changed_when: mount_check.rc == 0

- name: Ensure /etc/fstab entry for the disk (ensure remount after reboot)
  lineinfile:
    path: /etc/fstab
    line: "{{ disk_for_persistent_storage }}1 {{ export_path }} btrfs defaults 0 0"
    state: present

- name: Install NFS server
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: true
  become: true

- name: Configure NFS export
  lineinfile:
    path: /etc/exports
    line: "{{ export_path }} {{ nfs_network }}(rw,sync,no_root_squash)"
    state: present
    create: true
  become: true

- name: Restart NFS service
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: true
  changed_when: false
  become: true

- name: Verify the NFS export
  command: exportfs -v
  register: exportfs_output
  changed_when: false

- name: Ensure rpcbind service is running
  service:
    name: rpcbind
    state: started
    enabled: true
  become: true

- name: Ensure NFS service is running
  service:
    name: nfs-kernel-server
    state: started
    enabled: true
  become: true

- name: Display NFS export confirmation
  debug:
    msg: "NFS export configured: {{ exportfs_output.stdout }}"